# MongoDB connection
spring.application.name=movies
spring.mongodb.database=${MONGO_DATABASE}
spring.mongodb.uri=mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_CLUSTER}

# Steam API Key mapping
steam.api.key=${STEAM_API_KEY}

# JWT stuff
jwt.secret=your-super-secret-key-change-thi
jwt.expiration=86400000