package dev.chuong.movies.core.auth;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.bson.types.ObjectId;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

@Document(collection = "app_users")   // separate collection from Steam "users"
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Account {
    @Id
    private ObjectId id;              // auto-generated by MongoDB
    @Indexed(unique = true)           // no duplicate usernames in DB
    private String username;
    @Indexed(unique = true)           // no duplicate emails in DB
    private String email;
    private String password;          // BCrypt hashed — never store plain text
    private String role = "USER";     // default role: USER | ADMIN

    // Future Development: link a normal account to a Steam account later
    private String steamId;

    // Constructor used by AuthService during registration
    public Account(String username, String email, String password) {
        this.username = username;
        this.email    = email;
        this.password = password;
    }
}
